### ISSUE TITLE
WASM Example

### ISSUE THREAD

**Issue by araffin** [fragcolor-xyz/nimtorch#13]
Hello,

First, thank you for this cool project.
I was looking for the best/easiest approach to use torch in a browser (now that there is a C++ api, it should be easier to integrate) and it seems that this project can do the job.
However, in the README, only compilation instructions are given.
Could you point me/provide a basic example of how to use nimtorch from javascript ?

**Comment by sinkingsugar** [comment]
I completely missed this issue!

I plan to improve the wasm experience cos indeed at the moment there is not so much. And actually indeed it's not so easy to use without deep nim knowledge.

**Comment by sinkingsugar** [comment]
I added a wasm example, I hope you find it useful and if you have any feedback feel free to let us know :+1: 

https://github.com/fragcolor-xyz/nimtorch/tree/master/examples/webassembly

**Comment by araffin** [comment]
@sinkingsugar thanks, I just tried it and apparently there is a memory leak :/ (takes all my 8GB RAM)
Also, it does not show any output in firefox console (on chrome it does).

**Comment by araffin** [comment]
>Did you use all from conda ?

Yes, all from conda. My env:

```
name: nimtorch
channels:
  - fragcolor
  - defaults
dependencies:
  - aten=2018.12.30.1989=wasm_0
  - fragments=0.1.25=0
  - nim=0.19.9.1=0
  - nimtorch=2018.12.30.1989=0
  - wasm=1.0=0
```

emcc (Emscripten gcc/clang-like replacement) 1.38.16 (commit 7a0e27441eda6cb0e3f1210e6837cae4b080ab4c)

**Comment by sinkingsugar** [comment]
Small update: It definitely leaks/uses memory for me but not so much (max 1GB) I suspect it's also emcc related altho I'm just on 1.38.20 (not too much difference)

**Comment by araffin** [comment]
I upgraded to 1.38.21 and retested, the leak happens on both browser (more on firefox)
now the output shows properly in firefox. The leak is ~2GB on chrome and >3GB on firefox (also, at the end of training, some memory is released)

**Comment by sinkingsugar** [comment]
I actually found a major leak issue in any build :( probably related to the new compilation time optimization issues. We will release a fix soon!

**Comment by sinkingsugar** [comment]
small update: In this specific case we are not really detecting any leaks nim side, I will investigate further but it seems to inflate the memory during wasm compilation/bootstrap :(

**Comment by sinkingsugar** [comment]
I confused this issue with some other nim GC issue, we are investigating! but as I said before it might very well be related to emscripten and aten being big and as well gc:regions wasting memory.
