### ISSUE TITLE
can't install with nimble

### ISSUE THREAD

**Issue by retsyo** [fragcolor-xyz/nimtorch#2]
$ nim --version
Nim Compiler Version 0.18.1 [Windows: amd64]
Compiled at 2018-08-18
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: b5171f57ef00bffb12387d7daf3487c5e07645f9
active boot switches: -d:release

$ nimble install nimtorch
    Prompt: nimtorch not found in any local packages.json, check internet for updated packages? [y/N]
y
    Answer: Downloading Official package list
    Success Package list downloaded.
       Tip: 3 messages have been suppressed, use --verbose to show them.
     Error: Package not found.

**Comment by sinkingsugar** [comment]
Sadly depends on this PR: https://github.com/nim-lang/packages/pull/846 :(

**Comment by sinkingsugar** [comment]
There was a issue and we fixed it. Now waiting for the PR to be merged! Thank you for the report @retsyo !

**Comment by sinkingsugar** [comment]
Should be fine now!
