### ISSUE TITLE
OSX: building ATEN via `docker build -t docker_aten_native .` fails

### ISSUE THREAD

**Issue by timotheecour** [fragcolor-xyz/nimtorch#5]
> Download ATen binaries or build it (instructions under)

=> no OSX option

> ATen build instructions

> cd docker && cd docker-aten-native

is that a typo?

is my best bet to try to follow instructions from https://github.com/pytorch/pytorch or https://github.com/pytorch/pytorch/tree/master/aten ?

**Comment by sinkingsugar** [comment]
Might also have to fix some stuff in torch_cpp.nim

I plan to setup CI and conda builds for Mac OS X maybe next week.

**Comment by timotheecour** [comment]
`docker build -t docker_aten_native .` fails:

it goes fast until reaching this:
`[ 45%] Building CXX object src/ATen/CMakeFiles/ATen_cpu.dir/__/TH/THTensorConv.cpp.o` 
then it gets stuck (20min?) and finally fails with:

```
[ 45%] Building CXX object src/ATen/CMakeFiles/ATen_cpu.dir/__/TH/THTensorMath.cpp.o
/root/pytorch/aten/src/TH/THAllocator.cpp: In constructor 'THMapAllocator::THMapAllocator(WithFd, const char*, int, int, size_t)':
/root/pytorch/aten/src/TH/THAllocator.cpp:256:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if (size > file_stat.st_size) {
           ~~~~~^~~~~~~~~~~~~~~~~~~
/root/pytorch/aten/src/TH/THAllocator.cpp:261:64: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           if (fstat(fd, &file_stat) == -1 || file_stat.st_size < size) {
                                              ~~~~~~~~~~~~~~~~~~^~~~~~
/root/pytorch/aten/src/TH/THAllocator.cpp: In member function 'void THRefcountedMapAllocator::initializeAlloc()':
/root/pytorch/aten/src/TH/THAllocator.cpp:436:9: warning: unused variable 'data' [-Wunused-variable]
   char *data = ((char*)base_ptr_) + TH_ALLOC_ALIGNMENT;
         ^~~~
At global scope:
cc1plus: warning: unrecognized command line option '-Wno-unknown-warning-option'
cc1plus: warning: unrecognized command line option '-Wno-absolute-value'
[ 45%] Building CXX object src/ATen/CMakeFiles/ATen_cpu.dir/__/TH/THTensorMoreMath.cpp.o
[ 45%] Building CXX object src/ATen/CMakeFiles/ATen_cpu.dir/__/TH/THTensorEvenMoreMath.cpp.o
/root/pytorch/aten/src/TH/THTensor.cpp: In function 'at::optional<std::vector<long int> > THTensor_compute_stride(at::IntList, at::IntList, at::IntList)':
/root/pytorch/aten/src/TH/THTensor.cpp:158:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if (view_d == newshape.size() - 1) {
           ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
/root/pytorch/aten/src/TH/THTensor.cpp:156:13: warning: unused variable 'view_numel' [-Wunused-variable]
     int64_t view_numel = 1;
             ^~~~~~~~~~
[ 45%] Building CXX object src/ATen/CMakeFiles/ATen_cpu.dir/__/TH/THTensorConv.cpp.o
The command '/bin/sh -c cd && cd pytorch/aten && mkdir built && cd built && cmake -DCMAKE_BUILD_TYPE=Release -DUSE_CUDNN=OFF -DATEN_NO_TEST=ON -DCAFFE2_CMAKE_BUILDING_WITH_MAIN_REPO=OFF -DCMAKE_INSTALL_PREFIX=`pwd`/output ../ && make -j10 && make install -j10 && make clean && cp ../../tools/autograd/derivatives.yaml `pwd`/output/share/' returned a non-zero code: 137
```

**Comment by sinkingsugar** [comment]
I think gets stuck when building cuda stuff. 

Thing is that anyway for OS X you probably don't want to use docker.

I will try to get it running on MacOS this weekend! Got a build agent ready for that :)

**Comment by sinkingsugar** [comment]
Got it running on macos.

Just polishing up some automation to keep this repo in sync with PyTorch and release!

**Comment by timotheecour** [comment]
thanks! not seeing any new commits so I guess I'll wait for an update here

**Comment by sinkingsugar** [comment]
Still a bit manual, will try to make an automated build soon but this should get it running:

https://github.com/fragcolor-xyz/nimtorch/tree/nightly branch has macOS required fixes.

To build aten:
copy git commit hash from `torch/commit.txt`
```
- git clone -b fragcolor-devel https://github.com/fragcolor-xyz/pytorch.git
- cd pytorch
- git reset --hard <commit hash>
- mkdir built
- cd built
- cmake -DCMAKE_BUILD_TYPE=Release -DUSE_CUDA=OFF -DBUILD_ATEN_ONLY=ON -DCMAKE_INSTALL_PREFIX=`pwd`/output ../
- make
- make install
```

**Comment by timotheecour** [comment]
-- Checking for [mkl - guide - pthread - m]
--   Library mkl: not found
CMake Warning at cmake/Dependencies.cmake:76 (message):
  MKL could not be found.  Defaulting to Eigen
Call Stack (most recent call first):
  CMakeLists.txt:202 (include)

...
-- Performing Test C_HAS_THREAD
-- Performing Test C_HAS_THREAD - Success
Traceback (most recent call last):
  File "/Users/timothee/git_clone/nim/pytorch/cmake/../aten/src/ATen/gen.py", line 5, in <module>
    import yaml
ImportError: No module named yaml
--
CMake Error at cmake/Codegen.cmake:163 (message):
  Failed to get generated_cpp list
Call Stack (most recent call first):
  caffe2/CMakeLists.txt:2 (include)


-- Configuring incomplete, errors occurred!
See also "/Users/timothee/git_clone/nim/pytorch/built/CMakeFiles/CMakeOutput.log".
See also "/Users/timothee/git_clone/nim/pytorch/built/CMakeFiles/CMakeError.log".

**Comment by sinkingsugar** [comment]
oh yeah you will need `python` and `pyyaml` module.

btw, I'm going to release a conda osx version within today/tomorrow probably

**Comment by timotheecour** [comment]
`cmake ... etc` worked after I ran:
```
pip2 install pyyaml
pip2 install typing
```

great :)

> btw, I'm going to release a conda osx version within today/tomorrow probably

instead (or in addition to) a binary release, how about a `homebrew` formula? (as a side note, could also be used in linux via linuxbrew)

**Comment by sinkingsugar** [comment]
OSX support is now on master
