### ISSUE TITLE
[minor] `nim cpp -r torch.nim` => `nimble test` ? (more standard)

### ISSUE THREAD

**Issue by timotheecour** [fragcolor-xyz/nimtorch#6]

**Comment by sinkingsugar** [comment]
@jwollen What do you think? We are hardly using nimble much lately. People is already reluctant towards nim, conda is a better ticket in.

Altho yes, we could put all our tests in the nimble file on the other end.

**Comment by timotheecour** [comment]
> Altho yes, we could put all our tests in the nimble file on the other end.

well tests should be in a nim file, but `nimble test` should call them; at least that's what's standard in nim packages.
Following the most common convention makes things more discoverable and interoperable IMO, especially for tooling.

Here's a concrete example where this matters:
* https://github.com/nim-lang/Nim/issues/8638 would enable to run a whitelist of nimble packages; it requires having tests run in a standard way (via `nimble test`)

**Comment by sinkingsugar** [comment]
We added some tests in nimble file, `nimble test` works now. Coupled with other tasks too.

**Comment by sinkingsugar** [comment]
You need to copy some files back in the output folder in order to generate derivatives and declarations.

like:
```
RUN cd && \
cd pytorch && \
mkdir built && \
cd built && \
source activate deps && \
cmake -DCMAKE_INCLUDE_PATH=$CONDA_PREFIX/include -DCMAKE_LIBRARY_PATH=$CONDA_PREFIX/lib -DCMAKE_BUILD_TYPE=Release -DBUILD_ATEN_ONLY=ON -DCMAKE_INSTALL_PREFIX=`pwd`/output ../ && \
make -j10 && \
make install -j10 && \
make clean && \
cp ../tools/autograd/derivatives.yaml `pwd`/output/share/
```
I will add it to the readme soonish

**Comment by timotheecour** [comment]
nit: btw build is more common than built (that's what i had put in readme.md manual build instructions)

**Comment by sinkingsugar** [comment]
Do you think so? I'm actually curious about it.. 
I put lot of efforts for conda and workflow, specially for people coming from python and without any knowledge of nim.
Also I don't like nimble as package manager either.. often keeps renamed modules alive.. and other weird stuff...

**Comment by timotheecour** [comment]
* ok manually adding `cp ../tools/autograd/derivatives.yaml `pwd`/output/share/` made it work; just a bit verbose but ok; looks like `torch.nimble` is quite exhaustive...

> Also I don't like nimble as package manager either.. often keeps renamed modules alive.. and other weird stuff...

I actually quite like it :) not that it can't be improved, but compared to D's dub, this was a pleasant upgrade. Are there specific bugs in https://github.com/nim-lang/nimble/issues/ you're referring to? if they're not there we should definitely add a bug report so it doesn't get lost

* I think torch.nimble could be refactored as follows (untested):
```
let files = ["torch/generator.nim", ..., "tests/test_xor.nim"]
task test_cuda, "Run cuda gpu tests":
  for file in files:
    exec "nim cpp -r -o:test " & file
```

* all files have nim ext in that file except `torch` => use `torch.nim` ?

**Comment by sinkingsugar** [comment]
Nimble has a major flaw, which is it applies all the packages it has on every project you have by default. That's my major concern that easy can create a mess if not considered.

Do you mind we open a issue about those points above? no time right now but they make sense :)

**Comment by timotheecour** [comment]
> Do you mind we open a issue about those points above? no time right now but they make sense :)

=> https://github.com/fragcolor-xyz/nimtorch/issues/11

> Nimble has a major flaw, which is it applies all the packages it has on every project you have by default. That's my major concern that easy can create a mess if not considered.

I'd like to understand what you're referring to here; when you have time, do you mind providing more details in particular what kind of mess it can create, and what you'd want it to do instead ? if not a minimal test case at least enough info :-)
* the assumption is every package has a unique name, so there should be no name clash; 
* if nimble is aware of packages foo1 foo2 foo3 foo4, and package foo4 depends only on foo1 foo2, when building foo4 it shouln't have to build foo3; but maybe I'm misunderstanding

**Comment by sinkingsugar** [comment]
Thank you!

I will give you an example exactly with nimtorch:
* Have nimtorch installed as nimble package
* Also work on the repository
* Did not run `nimble develop`
* Rename a file in the repository
* Forget to update the module `import myrenamedfile` into `import newlocation/myrenamedfile`
* Build will succeed yet will use `import myrenamedfile` from nimble this time..

**Comment by timotheecour** [comment]
=> moved to https://github.com/fragcolor-xyz/nimtorch/issues/12 to keep each issue separate
